package frc.robot.autos;

public enum ChorPaths {
  PRELOAD_ONLY_LEFT("PRELOAD_ONLY_LEFT"),
  PRELOAD_ONLY_RIGHT("PRELOAD_ONLY_RIGHT"),

  // left
  LTRENCH_LNEUTRAL1("LTRENCH_LNEUTRAL1"),
  LNEUTRAL_LTRENCH("LNEUTRAL_LTRENCH"),
  LTRENCH_HUB("LTRENCH_HUB"),
  LNEUTRAL_LBUMP("LNEUTRAL_LBUMP1"),
  //
  LT_DELAY_SWIPE("LT_DELAY_SWIPE"),
  LBUMP_START("LBUMP_START"),
  DEPOT_PICKUP("DEPOT_PICKUP"),
  LBUMP_HUB("LBUMP_HUB"),
  DEPOT_SCORE("DEPOT_SCORE"),
  DEPOT_RETURN("DEPOT_RETURN"),

  // right
  RTRENCH_RNEUTRAL1("RTRENCH_RNEUTRAL1"),
  RNEUTRAL_RTRENCH("RNEUTRAL_RTRENCH"),
  RTRENCH_HUB("RTRENCH_HUB"),
  RNEUTRAL_RBUMP("RNEUTRAL_RBUMP"),
  //
  RT_DELAY_SWIPE("RT_DELAY_SWIPE"),
  RBUMP_HUB("RBUMP_HUB"),

  // center
  CENTER_BACKUP("CENTER_BACKUP"),
  LBUMP_LNEUTRAL("LBUMP_NEUTRAL"),
  DEPOT_SWIPE("DEPOT_SWIPE"),
  RIGHT_PRELOAD_OUTPOST("RIGHT_PRELOAD_OUTPOST"),

  // swipes
  RBUMP_SWEIP1("RBUMP_SWIPE1"),
  LBUMP_SWIPE1("LBUMP_SWIPE1"),

  // mid
  MID_SWIPE("MID SWIPE"),
  RFULL_SWEEP1("RFULL_SWEEP1"),
  RFULL_SWEEP2("RFULL_SWEEP2"),

  // half sweeps
  RC("RC"),
  RC_RETURN("RC_RETURN"),
  LC("LC"),
  LC_RETURN("LC_RETURN");

  public String pathName;

  private ChorPaths(String pName) {
    pathName = pName;
  }

  public String getPathName() {
    return pathName;
  }
}
