package frc.robot.autos;

// spotless: off
public enum ChorPaths {
  PRELOAD_ONLY_LEFT("PRELOAD_ONLY_LEFT"),
  PRELOAD_ONLY_RIGHT("PRELOAD_ONLY_RIGHT"),

  // OUT from alliance zone
  RT_LOOP("RT_LOOP"),
  LT_LOOP("LT_LOOP"),
  LT_LOOP_CTCW("LT_LOOP_CTCW"),
  RT_LOOP_CTCW("RT_LOOP_CTCW"),
  LTRENCH_LNEUTRAL1("LTRENCH_LNEUTRAL1"),
  RTRENCH_RNEUTRAL1("RTRENCH_RNEUTRAL1"),

  // RETURN from alliance zone
  SLOWER_LNEUTRALBUMP("SLOWER_LNEUTRALBUMP"),
  SLOWER_RNEUTRALRBUMP("SLOWER_RNEUTRALRBUMP"),
  LNEUTRAL_LTRENCH("LNEUTRAL_LTRENCH"),

  LTRENCH_HUB("LTRENCH_HUB"),
  LNEUTRAL_LBUMP("LNEUTRAL_LBUMP1"),
  LTRENCH_LNEUTRAL2("LTRENCH_LNEUTRAL2"),

  LT_DELAY_SWIPE("LT_DELAY_SWIPE"),
  LBUMP_START("LBUMP_START"),
  DEPOT_PICKUP("DEPOT_PICKUP"),
  LBUMP_HUB("LBUMP_HUB"), // neutral zone first
  LBUMP_HUB_SHORT("LBUMP_HUB_SHORT"),
  LBUMP_HUB2("LBUMP_HUB2"), // behind the hub first
  LBUMP_HUB2_SHORT("LBUMP_HUB2_SHORT"),
  DEPOT_SCORE("DEPOT_SCORE"),
  DEPOT_RETURN("DEPOT_RETURN"),

  // right

  RNEUTRAL_RTRENCH("RNEUTRAL_RTRENCH"),
  RTRENCH_HUB("RTRENCH_HUB"),
  RNEUTRAL_RBUMP("RNEUTRAL_RBUMP"),
  RTRENCH_RNEUTRAL2("RTRENCH_RNEUTRAL2"),
  //
  RT_DELAY_SWIPE("RT_DELAY_SWIPE"),
  RBUMP_HUB("RBUMP_HUB"), // neutral zone first
  RBUMP_HUB_SHORT("RBUMP_HUB_SHORT"),
  RBUMP_HUB2("RBUMP_HUB2"), // behind the hub first
  RBUMP_HUB2_SHORT("RBUMP_HUB2_SHORT"),

  // center
  CENTER_BACKUP("CENTER_BACKUP"),
  LBUMP_LNEUTRAL("LBUMP_NEUTRAL"),
  DEPOT_SWIPE("DEPOT_SWIPE"),
  RIGHT_PRELOAD_OUTPOST("RIGHT_PRELOAD_OUTPOST"),

  // swipes
  RBUMP_SWEIP1("RBUMP_SWIPE1"),
  LBUMP_SWIPE1("LBUMP_SWIPE1"),

  // mid
  MID_SWIPE("MID SWIPE"),
  RFULL_SWEEP1("RFULL_SWEEP1"),
  RFULL_SWEEP2("RFULL_SWEEP2"),

  // half sweeps
  RC("RC"),
  RC_RETURN("RC_RETURN"),
  LC("LC"),
  LC_RETURN("LC_RETURN");

  public String pathName;

  private ChorPaths(String pName) {
    pathName = pName;
  }

  public String getPathName() {
    return pathName;
  }
}

// spotless: on
