package frc.robot.autos;

public enum ChorPaths {
  PRELOAD_ONLY_LEFT("PRELOAD_ONLY_LEFT"), 
  PRELOAD_ONLY_RIGHT("PRELOAD_ONLY_RIGHT"), 

  // left
  LTRENCH_LNEUTRAL1("LTRENCH_LNEUTRAL1"), 
  LNEUTRAL_LTRENCH("LNEUTRAL_LTRENCH"), 
  LTRENCH_HUB("LTRENCH_HUB"), 
  LNEUTRAL_LBUMP("LNEUTRAL_LBUMP"), 
  //
  LT_DELAY_SWIPE("LT_DELAY_SWIPE"),
  LBUMP_START("LBUMP_START"),
  DEPOT_PICKUP("DEPOT_PICKUP"),
  DEPOT_SCORE("DEPOT_SCORE"),

  // right
  RTRENCH_RNEUTRAL1("RTRENCH_RNEUTRAL1"),
  RNEUTRAL_RTRENCH("RNEUTRAL_RTRENCH"), 
  RTRENCH_HUB("RTRENCH_HUB"), 
  RNEUTRAL_RBUMP("RNEUTRAL_RBUMP"),
  //
  RT_DELAY_SWIPE("RT_DELAY_SWIPE"),

  // center
  CENTER_BACKUP("CENTER_BACKUP"),
  LBUMP_LNEUTRAL("LBUMP_NEUTRAL"),
  DEPOT_SWIPE("DEPOT_SWIPE"),
  RIGHT_PRELOAD_OUTPOST("RIGHT_PRELOAD_OUTPOST"),
  
  // mid
  MID_SWIPE("MID SWIPE"),
  RFULL_SWEEP1("RFULL_SWEEP1"),
  RFULL_SWEEP2("RFULL_SWEEP2");

  public String pathName;

  private ChorPaths(String pName) {
    pathName = pName;
  }

  public String getPathName() {
    return pathName;
  }
}
